//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VTP2015.DataAccess.Identity {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Identity Management WebserviceSoap", Namespace="http://services.howest.be/")]
    public partial class IdentityManagementWebservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUserByUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByNameAndDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateUserByEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateActiveDirectoryByEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateUserByUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersWhosBirthdayIsTodayOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersWhosBirthdayIsOnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserBySourceAndSourceIdValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersBySearchStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartementenByUserIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IdentityManagementWebservice() {
            this.Url = global::VTP2015.DataAccess.Properties.Settings.Default.VTP2015_DataAccess_Identity_Identity_x0020_Management_x0020_Webservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUserByUsernameCompletedEventHandler GetUserByUsernameCompleted;
        
        /// <remarks/>
        public event GetUserByIdCompletedEventHandler GetUserByIdCompleted;
        
        /// <remarks/>
        public event GetUserByNameAndDateCompletedEventHandler GetUserByNameAndDateCompleted;
        
        /// <remarks/>
        public event GetUserByEmailCompletedEventHandler GetUserByEmailCompleted;
        
        /// <remarks/>
        public event AuthenticateUserByEmailCompletedEventHandler AuthenticateUserByEmailCompleted;
        
        /// <remarks/>
        public event AuthenticateActiveDirectoryByEmailCompletedEventHandler AuthenticateActiveDirectoryByEmailCompleted;
        
        /// <remarks/>
        public event AuthenticateUserByUsernameCompletedEventHandler AuthenticateUserByUsernameCompleted;
        
        /// <remarks/>
        public event GetUserTypesCompletedEventHandler GetUserTypesCompleted;
        
        /// <remarks/>
        public event GetUsersCompletedEventHandler GetUsersCompleted;
        
        /// <remarks/>
        public event GetUsersWhosBirthdayIsTodayCompletedEventHandler GetUsersWhosBirthdayIsTodayCompleted;
        
        /// <remarks/>
        public event GetUsersWhosBirthdayIsOnCompletedEventHandler GetUsersWhosBirthdayIsOnCompleted;
        
        /// <remarks/>
        public event GetUserBySourceAndSourceIdValueCompletedEventHandler GetUserBySourceAndSourceIdValueCompleted;
        
        /// <remarks/>
        public event GetUsersBySearchStringCompletedEventHandler GetUsersBySearchStringCompleted;
        
        /// <remarks/>
        public event GetDepartementenByUserIdCompletedEventHandler GetDepartementenByUserIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUserByUsername", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetUserByUsername(string username) {
            object[] results = this.Invoke("GetUserByUsername", new object[] {
                        username});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByUsernameAsync(string username) {
            this.GetUserByUsernameAsync(username, null);
        }
        
        /// <remarks/>
        public void GetUserByUsernameAsync(string username, object userState) {
            if ((this.GetUserByUsernameOperationCompleted == null)) {
                this.GetUserByUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByUsernameOperationCompleted);
            }
            this.InvokeAsync("GetUserByUsername", new object[] {
                        username}, this.GetUserByUsernameOperationCompleted, userState);
        }
        
        private void OnGetUserByUsernameOperationCompleted(object arg) {
            if ((this.GetUserByUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByUsernameCompleted(this, new GetUserByUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUserById", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetUserById(string id) {
            object[] results = this.Invoke("GetUserById", new object[] {
                        id});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByIdAsync(string id) {
            this.GetUserByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetUserByIdAsync(string id, object userState) {
            if ((this.GetUserByIdOperationCompleted == null)) {
                this.GetUserByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByIdOperationCompleted);
            }
            this.InvokeAsync("GetUserById", new object[] {
                        id}, this.GetUserByIdOperationCompleted, userState);
        }
        
        private void OnGetUserByIdOperationCompleted(object arg) {
            if ((this.GetUserByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByIdCompleted(this, new GetUserByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUserByNameAndDate", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetUserByNameAndDate(string lastname, string firstname, string dateOfBirth) {
            object[] results = this.Invoke("GetUserByNameAndDate", new object[] {
                        lastname,
                        firstname,
                        dateOfBirth});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByNameAndDateAsync(string lastname, string firstname, string dateOfBirth) {
            this.GetUserByNameAndDateAsync(lastname, firstname, dateOfBirth, null);
        }
        
        /// <remarks/>
        public void GetUserByNameAndDateAsync(string lastname, string firstname, string dateOfBirth, object userState) {
            if ((this.GetUserByNameAndDateOperationCompleted == null)) {
                this.GetUserByNameAndDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByNameAndDateOperationCompleted);
            }
            this.InvokeAsync("GetUserByNameAndDate", new object[] {
                        lastname,
                        firstname,
                        dateOfBirth}, this.GetUserByNameAndDateOperationCompleted, userState);
        }
        
        private void OnGetUserByNameAndDateOperationCompleted(object arg) {
            if ((this.GetUserByNameAndDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByNameAndDateCompleted(this, new GetUserByNameAndDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUserByEmail", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetUserByEmail(string email) {
            object[] results = this.Invoke("GetUserByEmail", new object[] {
                        email});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByEmailAsync(string email) {
            this.GetUserByEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void GetUserByEmailAsync(string email, object userState) {
            if ((this.GetUserByEmailOperationCompleted == null)) {
                this.GetUserByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByEmailOperationCompleted);
            }
            this.InvokeAsync("GetUserByEmail", new object[] {
                        email}, this.GetUserByEmailOperationCompleted, userState);
        }
        
        private void OnGetUserByEmailOperationCompleted(object arg) {
            if ((this.GetUserByEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByEmailCompleted(this, new GetUserByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/AuthenticateUserByEmail", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AuthenticateUserByEmail(string email, string password) {
            object[] results = this.Invoke("AuthenticateUserByEmail", new object[] {
                        email,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserByEmailAsync(string email, string password) {
            this.AuthenticateUserByEmailAsync(email, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserByEmailAsync(string email, string password, object userState) {
            if ((this.AuthenticateUserByEmailOperationCompleted == null)) {
                this.AuthenticateUserByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserByEmailOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUserByEmail", new object[] {
                        email,
                        password}, this.AuthenticateUserByEmailOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserByEmailOperationCompleted(object arg) {
            if ((this.AuthenticateUserByEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserByEmailCompleted(this, new AuthenticateUserByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/AuthenticateActiveDirectoryByEmail", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AuthenticateActiveDirectoryByEmail(string email, string password) {
            object[] results = this.Invoke("AuthenticateActiveDirectoryByEmail", new object[] {
                        email,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateActiveDirectoryByEmailAsync(string email, string password) {
            this.AuthenticateActiveDirectoryByEmailAsync(email, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateActiveDirectoryByEmailAsync(string email, string password, object userState) {
            if ((this.AuthenticateActiveDirectoryByEmailOperationCompleted == null)) {
                this.AuthenticateActiveDirectoryByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateActiveDirectoryByEmailOperationCompleted);
            }
            this.InvokeAsync("AuthenticateActiveDirectoryByEmail", new object[] {
                        email,
                        password}, this.AuthenticateActiveDirectoryByEmailOperationCompleted, userState);
        }
        
        private void OnAuthenticateActiveDirectoryByEmailOperationCompleted(object arg) {
            if ((this.AuthenticateActiveDirectoryByEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateActiveDirectoryByEmailCompleted(this, new AuthenticateActiveDirectoryByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/AuthenticateUserByUsername", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AuthenticateUserByUsername(string username, string password) {
            object[] results = this.Invoke("AuthenticateUserByUsername", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserByUsernameAsync(string username, string password) {
            this.AuthenticateUserByUsernameAsync(username, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserByUsernameAsync(string username, string password, object userState) {
            if ((this.AuthenticateUserByUsernameOperationCompleted == null)) {
                this.AuthenticateUserByUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserByUsernameOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUserByUsername", new object[] {
                        username,
                        password}, this.AuthenticateUserByUsernameOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserByUsernameOperationCompleted(object arg) {
            if ((this.AuthenticateUserByUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserByUsernameCompleted(this, new AuthenticateUserByUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUserTypes", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserType[] GetUserTypes() {
            object[] results = this.Invoke("GetUserTypes", new object[0]);
            return ((UserType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserTypesAsync() {
            this.GetUserTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetUserTypesAsync(object userState) {
            if ((this.GetUserTypesOperationCompleted == null)) {
                this.GetUserTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserTypesOperationCompleted);
            }
            this.InvokeAsync("GetUserTypes", new object[0], this.GetUserTypesOperationCompleted, userState);
        }
        
        private void OnGetUserTypesOperationCompleted(object arg) {
            if ((this.GetUserTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserTypesCompleted(this, new GetUserTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUsers", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] GetUsers(UserTypeId userTypeId) {
            object[] results = this.Invoke("GetUsers", new object[] {
                        userTypeId});
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersAsync(UserTypeId userTypeId) {
            this.GetUsersAsync(userTypeId, null);
        }
        
        /// <remarks/>
        public void GetUsersAsync(UserTypeId userTypeId, object userState) {
            if ((this.GetUsersOperationCompleted == null)) {
                this.GetUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersOperationCompleted);
            }
            this.InvokeAsync("GetUsers", new object[] {
                        userTypeId}, this.GetUsersOperationCompleted, userState);
        }
        
        private void OnGetUsersOperationCompleted(object arg) {
            if ((this.GetUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUsersWhosBirthdayIsToday", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] GetUsersWhosBirthdayIsToday() {
            object[] results = this.Invoke("GetUsersWhosBirthdayIsToday", new object[0]);
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersWhosBirthdayIsTodayAsync() {
            this.GetUsersWhosBirthdayIsTodayAsync(null);
        }
        
        /// <remarks/>
        public void GetUsersWhosBirthdayIsTodayAsync(object userState) {
            if ((this.GetUsersWhosBirthdayIsTodayOperationCompleted == null)) {
                this.GetUsersWhosBirthdayIsTodayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersWhosBirthdayIsTodayOperationCompleted);
            }
            this.InvokeAsync("GetUsersWhosBirthdayIsToday", new object[0], this.GetUsersWhosBirthdayIsTodayOperationCompleted, userState);
        }
        
        private void OnGetUsersWhosBirthdayIsTodayOperationCompleted(object arg) {
            if ((this.GetUsersWhosBirthdayIsTodayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersWhosBirthdayIsTodayCompleted(this, new GetUsersWhosBirthdayIsTodayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUsersWhosBirthdayIsOn", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] GetUsersWhosBirthdayIsOn(int month, int day) {
            object[] results = this.Invoke("GetUsersWhosBirthdayIsOn", new object[] {
                        month,
                        day});
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersWhosBirthdayIsOnAsync(int month, int day) {
            this.GetUsersWhosBirthdayIsOnAsync(month, day, null);
        }
        
        /// <remarks/>
        public void GetUsersWhosBirthdayIsOnAsync(int month, int day, object userState) {
            if ((this.GetUsersWhosBirthdayIsOnOperationCompleted == null)) {
                this.GetUsersWhosBirthdayIsOnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersWhosBirthdayIsOnOperationCompleted);
            }
            this.InvokeAsync("GetUsersWhosBirthdayIsOn", new object[] {
                        month,
                        day}, this.GetUsersWhosBirthdayIsOnOperationCompleted, userState);
        }
        
        private void OnGetUsersWhosBirthdayIsOnOperationCompleted(object arg) {
            if ((this.GetUsersWhosBirthdayIsOnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersWhosBirthdayIsOnCompleted(this, new GetUsersWhosBirthdayIsOnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUserBySourceAndSourceIdValue", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetUserBySourceAndSourceIdValue(int sourceId, string sourceIdValue) {
            object[] results = this.Invoke("GetUserBySourceAndSourceIdValue", new object[] {
                        sourceId,
                        sourceIdValue});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserBySourceAndSourceIdValueAsync(int sourceId, string sourceIdValue) {
            this.GetUserBySourceAndSourceIdValueAsync(sourceId, sourceIdValue, null);
        }
        
        /// <remarks/>
        public void GetUserBySourceAndSourceIdValueAsync(int sourceId, string sourceIdValue, object userState) {
            if ((this.GetUserBySourceAndSourceIdValueOperationCompleted == null)) {
                this.GetUserBySourceAndSourceIdValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserBySourceAndSourceIdValueOperationCompleted);
            }
            this.InvokeAsync("GetUserBySourceAndSourceIdValue", new object[] {
                        sourceId,
                        sourceIdValue}, this.GetUserBySourceAndSourceIdValueOperationCompleted, userState);
        }
        
        private void OnGetUserBySourceAndSourceIdValueOperationCompleted(object arg) {
            if ((this.GetUserBySourceAndSourceIdValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserBySourceAndSourceIdValueCompleted(this, new GetUserBySourceAndSourceIdValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetUsersBySearchString", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] GetUsersBySearchString(string searchstring) {
            object[] results = this.Invoke("GetUsersBySearchString", new object[] {
                        searchstring});
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersBySearchStringAsync(string searchstring) {
            this.GetUsersBySearchStringAsync(searchstring, null);
        }
        
        /// <remarks/>
        public void GetUsersBySearchStringAsync(string searchstring, object userState) {
            if ((this.GetUsersBySearchStringOperationCompleted == null)) {
                this.GetUsersBySearchStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersBySearchStringOperationCompleted);
            }
            this.InvokeAsync("GetUsersBySearchString", new object[] {
                        searchstring}, this.GetUsersBySearchStringOperationCompleted, userState);
        }
        
        private void OnGetUsersBySearchStringOperationCompleted(object arg) {
            if ((this.GetUsersBySearchStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersBySearchStringCompleted(this, new GetUsersBySearchStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.howest.be/GetDepartementenByUserId", RequestNamespace="http://services.howest.be/", ResponseNamespace="http://services.howest.be/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Departement[] GetDepartementenByUserId(string userId) {
            object[] results = this.Invoke("GetDepartementenByUserId", new object[] {
                        userId});
            return ((Departement[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartementenByUserIdAsync(string userId) {
            this.GetDepartementenByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetDepartementenByUserIdAsync(string userId, object userState) {
            if ((this.GetDepartementenByUserIdOperationCompleted == null)) {
                this.GetDepartementenByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartementenByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetDepartementenByUserId", new object[] {
                        userId}, this.GetDepartementenByUserIdOperationCompleted, userState);
        }
        
        private void OnGetDepartementenByUserIdOperationCompleted(object arg) {
            if ((this.GetDepartementenByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartementenByUserIdCompleted(this, new GetDepartementenByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.howest.be/")]
    public partial class User {
        
        private string idField;
        
        private UserTypeSource[] userTypeSourcesField;
        
        private string usernameField;
        
        private string emailField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private System.DateTime dateOfBirthField;
        
        private string extraInfo1Field;
        
        private string extraInfo2Field;
        
        private UserDomain[] userDomainsField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public UserTypeSource[] UserTypeSources {
            get {
                return this.userTypeSourcesField;
            }
            set {
                this.userTypeSourcesField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string ExtraInfo1 {
            get {
                return this.extraInfo1Field;
            }
            set {
                this.extraInfo1Field = value;
            }
        }
        
        /// <remarks/>
        public string ExtraInfo2 {
            get {
                return this.extraInfo2Field;
            }
            set {
                this.extraInfo2Field = value;
            }
        }
        
        /// <remarks/>
        public UserDomain[] UserDomains {
            get {
                return this.userDomainsField;
            }
            set {
                this.userDomainsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.howest.be/")]
    public partial class UserTypeSource {
        
        private UserType userTypeField;
        
        private Source sourceField;
        
        private string sourceIdValueField;
        
        /// <remarks/>
        public UserType UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        public Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string SourceIdValue {
            get {
                return this.sourceIdValueField;
            }
            set {
                this.sourceIdValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.howest.be/")]
    public partial class UserType {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.howest.be/")]
    public partial class Departement {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.howest.be/")]
    public partial class UserDomain {
        
        private string domainField;
        
        private Source sourceField;
        
        /// <remarks/>
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        public Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.howest.be/")]
    public partial class Source {
        
        private int idField;
        
        private string nameField;
        
        private string fileLocationField;
        
        private string connectionstringField;
        
        private string sqlStatementField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string FileLocation {
            get {
                return this.fileLocationField;
            }
            set {
                this.fileLocationField = value;
            }
        }
        
        /// <remarks/>
        public string Connectionstring {
            get {
                return this.connectionstringField;
            }
            set {
                this.connectionstringField = value;
            }
        }
        
        /// <remarks/>
        public string SqlStatement {
            get {
                return this.sqlStatementField;
            }
            set {
                this.sqlStatementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.howest.be/")]
    public enum UserTypeId {
        
        /// <remarks/>
        Alumni,
        
        /// <remarks/>
        Studenten,
        
        /// <remarks/>
        Personeel,
        
        /// <remarks/>
        Bestuursleden,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserByUsernameCompletedEventHandler(object sender, GetUserByUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserByIdCompletedEventHandler(object sender, GetUserByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserByNameAndDateCompletedEventHandler(object sender, GetUserByNameAndDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByNameAndDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByNameAndDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserByEmailCompletedEventHandler(object sender, GetUserByEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void AuthenticateUserByEmailCompletedEventHandler(object sender, AuthenticateUserByEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void AuthenticateActiveDirectoryByEmailCompletedEventHandler(object sender, AuthenticateActiveDirectoryByEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateActiveDirectoryByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateActiveDirectoryByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void AuthenticateUserByUsernameCompletedEventHandler(object sender, AuthenticateUserByUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserByUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserByUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserTypesCompletedEventHandler(object sender, GetUserTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUsersCompletedEventHandler(object sender, GetUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUsersWhosBirthdayIsTodayCompletedEventHandler(object sender, GetUsersWhosBirthdayIsTodayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersWhosBirthdayIsTodayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersWhosBirthdayIsTodayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUsersWhosBirthdayIsOnCompletedEventHandler(object sender, GetUsersWhosBirthdayIsOnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersWhosBirthdayIsOnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersWhosBirthdayIsOnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserBySourceAndSourceIdValueCompletedEventHandler(object sender, GetUserBySourceAndSourceIdValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserBySourceAndSourceIdValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserBySourceAndSourceIdValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUsersBySearchStringCompletedEventHandler(object sender, GetUsersBySearchStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersBySearchStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersBySearchStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetDepartementenByUserIdCompletedEventHandler(object sender, GetDepartementenByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartementenByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartementenByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Departement[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Departement[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591